[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_BACKEND_URL = "https://apollo-scalping-bot-backend.onrender.com"

[context.deploy-preview.environment]
  VITE_BACKEND_URL = "https://apollo-scalping-bot-backend.onrender.com"