[start]
cmd = "python server.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
cmds = ["echo 'Apollo Scalping Bot - Direct Server Launch'"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python install_deps.py"
]

[phases.install]
cmds = ["echo 'Installing custom dependencies'"]

# Force custom startup
[providers]
python = true