[start]
cmd = "python run.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
cmds = ["echo 'Apollo Scalping Bot - Custom Python startup'"]

[phases.build]
cmds = ["pip install -r requirements.txt"]