[start]
cmd = "python main.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
cmds = ["echo 'Apollo Scalping Bot - Custom Python startup'"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.install]
cmds = ["echo 'Custom install phase'"]

# Disable auto-detection
[providers]
python = false